export enum ScrapeStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
}

export enum PairStatus {
  NOT_STARTED = "NOT_STARTED",
  COMPLETED = "COMPLETED",
  UNRESOLVED = "UNRESOLVED",
  PARTIAL = "PARTIAL",
}

export enum FetchStatus {
  NOT_STARTED = "NOT_STARTED",
  COMPLETED = "COMPLETED",
  PARTIAL = "PARTIAL",
}

export enum GlobalStatus {
  NOT_STARTED = "NOT_STARTED",
  COMPLETED = "COMPLETED",
  PARTIAL = "PARTIAL",
}