export enum ScrapeStatus {
  NOT_STARTED = "NOT_STARTED",
  COMPLETED_LIVE = "COMPLETED_LIVE",
  COMPLETED_DEAD = "COMPLETED_DEAD",
  COMPLETED_ENDED = "COMPLETED_ENDED",
}

export enum PairStatus {
  NOT_STARTED = "NOT_STARTED",
  COMPLETED = "COMPLETED",
  UNRESOLVED = "UNRESOLVED",
  PARTIAL = "PARTIAL",
}

export enum FetchStatus {
  NOT_STARTED = "NOT_STARTED",
  COMPLETED = "COMPLETED",
  PARTIAL = "PARTIAL",
}

export enum GlobalStatus {
  NOT_STARTED = "NOT_STARTED",
  COMPLETED = "COMPLETED",
  PARTIAL = "PARTIAL",
  FAILED = "FAILED",
}