coverage:
  status:
    project:
      default:
        target: auto  # Requires coverage to NOT drop from previous
        threshold: 0% # Allow very small fluctuations
    patch:
      default:
        target: 75%  # Require at least 85% coverage for new code
        threshold: 0% # Any reduction in coverage blocks PR
