pre_bump_hooks = [
  "pnpm -r run dev:build",
  "pnpm -r run test",
  "pnpm -r run lint"
]

post_bump_hooks = [
    "scripts/changelog.json.sh && git add extension/src/changelog.json && git commit -m 'chore(release): update changelog.json'",
    "tsx scripts/sync-version.ts && git add extension/package.json cloudflare-proxy/package.json CHANGELOG.md && git commit -m 'chore(release): sync package.json version'",
    "git push && git push --tags"
]

[changelog]
path = "CHANGELOG.md"

