pre_bump_hooks = [
    "pnpm lint",
    "pnpm test"
]

post_bump_hooks = [
    "pnpm sync-version && git add package.json CHANGELOG.md && git commit -m 'chore: sync package.json version'",
    "git push && git push --tags"
]

[changelog]
path = "CHANGELOG.md"

