pre_bump_hooks = [
    "pnpm lint",
    "pnpm test"
]

post_bump_hooks = [
    "pnpm sync-version && git add package.json && git commit -m 'chore: sync package.json version'"
]

[changelog]
path = "CHANGELOG.md"

