pre_bump_hooks = [
  "pnpm -r run dev:build",
  "pnpm -r run type-check",
  "pnpm -r run test",
  "pnpm -r run lint"
]

post_bump_hooks = [
  "scripts/changelog.json.sh",
  "pnpm exec tsx scripts/sync-version.ts",
  "git add extension/package.json cloudflare-proxy/package.json extension/src/changelog.json CHANGELOG.md",
  "git commit --amend --no-edit"
]

[changelog]
path = "CHANGELOG.md"

