blank_issues_enabled: false
contact_links:
  - name: General Inquiry
    url: https://github.com/Guibod/scrap-trawler/discussions
    about: For questions or discussions unrelated to bugs or feature requests.
