name: 🚀 Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    name: Release & Versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Install deps including tsx
        run: pnpm install --frozen-lockfile

      # Pre-bump: build to prepare plasmo
      - name: Dev build (extension)
        run: pnpm --filter extension run dev:build

      # 🔥 Perform the version bump (triggers hooks)
      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true
          git-user: 'Cog Bot'
          git-user-email: 'github-actions[bot]@users.noreply.github.com'

      # 🔧 Optional: zip + upload extension
      - name: Build release (plasmo)
        run: pnpm --filter extension build

      - name: Zip extension output
        run: |
          cd extension/build
          zip -r ../../scrap-trawler-${{ steps.release.outputs.version }}.zip .
          cd ../..

      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.release.outputs.version }}
          files: scrap-trawler-${{ steps.release.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          files: |
            extension/coverage/lcov.info
            cloudflare-proxy/coverage/lcov.info
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
